image: node:22-alpine

cache:
  paths:
    - node_modules/
    - .next/cache/

stages:
  - deploy

pages:
  stage: deploy
  script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm install --frozen-lockfile
    - pnpm build
    - rm -rf public
    - mv out public
  artifacts:
    paths:
      - public
  only:
    - main
